version: "3.1"

services:
  laravel_cards:
    build:
      context: .
      dockerfile: Dockerfile
    image: ta/advancebank
    container_name: cbaapp
    restart: always
    network_mode: host
    ports:
    - 9000:8080



